<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {

        $states = [
            '1' => 'Ceará',
            '2' => 'Maranhão',
            '3' => 'Piauí',
            '4' => 'Rio Grande do Norte'
        ];

        $cidadesCeara = [
            '1' => 'Abaiara',
            '2' => 'Acarape',
            '3' => 'Acarau',
            '4' => 'Acopiara',
            '5' => 'Aiuaba',
            '6' => 'Alcantaras',
            '7' => 'Altaneira',
            '8' => 'Alto Santo',
            '9' => 'Amontada',
            '10' => 'Antonina do Norte',
            '11' => 'Apuiares',
            '12' => 'Aquiraz',
            '13' => 'Aracati',
            '14' => 'Aracoiaba',
            '15' => 'Ararenda',
            '16' => 'Araripe',
            '17' => 'Aratuba',
            '18' => 'Arneiroz',
            '19' => 'Assare',
            '20' => 'Aurora',
            '21' => 'Baixio',
            '22' => 'Banabuiu',
            '23' => 'Barbalha',
            '24' => 'Barreira',
            '25' => 'Barro',
            '26' => 'Barroquinha',
            '27' => 'Baturite',
            '28' => 'Beberibe',
            '29' => 'Bela Cruz',
            '30' => 'Boa Viagem',
            '31' => 'Brejo Santo',
            '32' => 'Camocim',
            '33' => 'Campos Sales',
            '34' => 'Caninde',
            '35' => 'Capistrano',
            '36' => 'Caridade',
            '37' => 'Carire',
            '38' => 'Caririacu',
            '39' => 'Carius',
            '40' => 'Carnaubal',
            '41' => 'Cascavel',
            '42' => 'Catarina',
            '43' => 'Catunda',
            '44' => 'Caucaia',
            '45' => 'Cedro',
            '46' => 'Chaval',
            '47' => 'Choro',
            '48' => 'Chorozinho',
            '49' => 'Coreau',
            '50' => 'Crateus',
            '51' => 'Crato',
            '52' => 'Croata',
            '53' => 'Cruz',
            '54' => 'Deputado Irapuan Pinheiro',
            '55' => 'Erere',
            '56' => 'Eusebio',
            '57' => 'Farias Brito',
            '58' => 'Forquilha',
            '59' => 'Fortaleza',
            '60' => 'Fortim',
            '61' => 'Frecheirinha',
            '62' => 'General Sampaio',
            '63' => 'Graca',
            '64' => 'Granja',
            '65' => 'Granjeiro',
            '66' => 'Groairas',
            '67' => 'Guaiuba',
            '68' => 'Guaraciaba do Norte',
            '69' => 'Guaramiranga',
            '70' => 'Hidrolandia',
            '71' => 'Horizonte',
            '72' => 'Ibaretama',
            '73' => 'Ibiapina',
            '74' => 'Ibicuitinga',
            '75' => 'Icapui',
            '76' => 'Ico',
            '77' => 'Iguatu',
            '78' => 'Independencia',
            '79' => 'Ipaporanga',
            '80' => 'Ipaumirim',
            '81' => 'Ipu',
            '82' => 'Ipueiras',
            '83' => 'Iracema',
            '84' => 'Iraucuba',
            '85' => 'Itaicaba',
            '86' => 'Itaitinga',
            '87' => 'Itapage',
            '88' => 'Itapipoca',
            '89' => 'Itapiuna',
            '90' => 'Itarema',
            '91' => 'Itatira',
            '92' => 'Jaguaretama',
            '93' => 'Jaguaribara',
            '94' => 'Jaguaribe',
            '95' => 'Jaguaruana',
            '96' => 'Jardim',
            '97' => 'Jati',
            '98' => 'Jijoca de Jericoacoara',
            '99' => 'Juazeiro do Norte',
            '100' => 'Jucas',
            '101' => 'Lavras da Mangabeira',
            '102' => 'Limoeiro do Norte',
            '103' => 'Madalena',
            '104' => 'Maracanau',
            '105' => 'Maranguape',
            '106' => 'Marco',
            '107' => 'Martinopole',
            '108' => 'Massape',
            '109' => 'Mauriti',
            '110' => 'Meruoca',
            '111' => 'Milagres',
            '112' => 'Milha',
            '113' => 'Miraima',
            '114' => 'Missao Velha',
            '115' => 'Mombaca',
            '116' => 'Monsenhor Tabosa',
            '117' => 'Morada Nova',
            '118' => 'Moraujo',
            '119' => 'Morrinhos',
            '120' => 'Mucambo',
            '121' => 'Mulungu',
            '122' => 'Nova Olinda',
            '123' => 'Nova Russas',
            '124' => 'Novo Oriente',
            '125' => 'Ocara',
            '126' => 'Oros',
            '127' => 'Pacajus',
            '128' => 'Pacatuba',
            '129' => 'Pacoti',
            '130' => 'Pacuja',
            '131' => 'Palhano',
            '132' => 'Palmacia',
            '133' => 'Paracuru',
            '134' => 'Paraipaba',
            '135' => 'Parambu',
            '136' => 'Paramoti',
            '137' => 'Pedra Branca',
            '138' => 'Penaforte',
            '139' => 'Pentecoste',
            '140' => 'Pereiro',
            '141' => 'Pindoretama',
            '142' => 'Piquet Carneiro',
            '143' => 'Pires Ferreira',
            '144' => 'Poranga',
            '145' => 'Porteiras',
            '146' => 'Potengi',
            '147' => 'Potiretama',
            '148' => 'Quiterianopolis',
            '149' => 'Quixada',
            '150' => 'Quixela',
            '151' => 'Quixeramobim',
            '152' => 'Quixere',
            '153' => 'Redencao',
            '154' => 'Reriutaba',
            '155' => 'Russas',
            '156' => 'Saboeiro',
            '157' => 'Salitre',
            '158' => 'Santa Quiteria',
            '159' => 'Santana do Acarau',
            '160' => 'Santana do Cariri',
            '161' => 'Sao Benedito',
            '162' => 'Sao Goncalo do Amarante',
            '163' => 'Sao Joao do Jaguaribe',
            '164' => 'Sao Luis do Curu',
            '165' => 'Senador Pompeu',
            '166' => 'Senador Sa',
            '167' => 'Sobral',
            '168' => 'Solonopole',
            '169' => 'Tabuleiro do Norte',
            '170' => 'Tamboril',
            '171' => 'Tarrafas',
            '172' => 'Taua',
            '173' => 'Tejucuoca',
            '174' => 'Tiangua',
            '175' => 'Trairi',
            '176' => 'Tururu',
            '177' => 'Ubajara',
            '178' => 'Umari',
            '179' => 'Umirim',
            '180' => 'Uruburetama',
            '181' => 'Uruoca',
            '182' => 'Varjota',
            '183' => 'Varzea Alegre',
            '184' => 'Vicosa do Ceara',
        ];

        $cidadesMaranhao = [
            '185' => 'Acailandia',
            '186' => 'Afonso Cunha',
            '187' => 'Agua Doce do Maranhao',
            '188' => 'Alcantara',
            '189' => 'Aldeias Altas',
            '190' => 'Altamira do Maranhao',
            '191' => 'Alto Alegre do Maranhao',
            '192' => 'Alto Alegre do Pindare',
            '193' => 'Alto Parnaiba',
            '194' => 'Amapa do Maranhao',
            '195' => 'Amarante do Maranhao',
            '196' => 'Anajatuba',
            '197' => 'Anapurus',
            '198' => 'Apicum-Acu',
            '199' => 'Araguana',
            '200' => 'Araioses',
            '201' => 'Arame',
            '202' => 'Arari',
            '203' => 'Axixa',
            '204' => 'Bacabal',
            '205' => 'Bacabeira',
            '206' => 'Bacuri',
            '207' => 'Bacurituba',
            '208' => 'Balsas',
            '209' => 'Barao de Grajau',
            '210' => 'Barra do Corda',
            '211' => 'Barreirinhas',
            '212' => 'Bela Vista do Maranhao',
            '213' => 'Belagua',
            '214' => 'Benedito Leite',
            '215' => 'Bequimao',
            '216' => 'Bernardo do Mearim',
            '217' => 'Boa Vista do Gurupi',
            '218' => 'Bom Jardim',
            '219' => 'Bom Jesus das Selvas',
            '220' => 'Bom Lugar',
            '221' => 'Brejo de Areia',
            '222' => 'Brejo',
            '223' => 'Buriti Bravo',
            '224' => 'Buriti',
            '225' => 'Buriticupu',
            '226' => 'Buritirama',
            '227' => 'Cachoeira Grande',
            '228' => 'Cajapio',
            '229' => 'Cajari',
            '230' => 'Campestre do Maranhao',
            '231' => 'Candido Mendes',
            '232' => 'Cantanhede',
            '233' => 'Capinzal do Norte',
            '234' => 'Carolina',
            '235' => 'Carutapera',
            '236' => 'Caxias',
            '237' => 'Cedral',
            '238' => 'Central do Maranhao',
            '239' => 'Centro Novo do Maranhao',
            '240' => 'Centro do Guilherme',
            '241' => 'Chapadinha',
            '242' => 'Cidelandia',
            '243' => 'Codo',
            '244' => 'Coelho Neto',
            '245' => 'Colinas',
            '246' => 'Conceicao do Lago-Acu',
            '247' => 'Coroata',
            '248' => 'Cururupu',
            '249' => 'Davinopolis',
            '250' => 'Dom Pedro',
            '251' => 'Duque Bacelar',
            '252' => 'Esperantinopolis',
            '253' => 'Estreito',
            '254' => 'Feira Nova do Maranhao',
            '255' => 'Fernando Falcao',
            '256' => 'Formosa da Serra Negra',
            '257' => 'Fortaleza dos Nogueiras',
            '258' => 'Fortuna',
            '259' => 'Godofredo Viana',
            '260' => 'Goncalves Dias',
            '261' => 'Governador Archer',
            '262' => 'Governador Edison Lobao',
            '263' => 'Governador Eugenio Barros',
            '264' => 'Governador Luiz Rocha',
            '265' => 'Governador Newton Bello',
            '266' => 'Governador Nunes Freire',
            '267' => 'Graca Aranha',
            '268' => 'Grajau',
            '269' => 'Guimaraes',
            '270' => 'Humberto de Campos',
            '271' => 'Icatu',
            '272' => 'Igarape Grande',
            '273' => 'Igarape do Meio',
            '274' => 'Imperatriz',
            '275' => 'Itaipava do Grajau',
            '276' => 'Itapecuru Mirim',
            '277' => 'Itinga do Maranhao',
            '278' => 'Jatoba',
            '279' => 'Jenipapo dos Vieiras',
            '280' => 'Joao Lisboa',
            '281' => 'Joselandia',
            '282' => 'Junco do Maranhao',
            '283' => 'Lago Verde',
            '284' => 'Lago da Pedra',
            '285' => 'Lago do Junco',
            '286' => 'Lagoa Grande do Maranhao',
            '287' => 'Lagoa do Mato',
            '288' => 'Lagoa dos Rodrigues',
            '289' => 'Lajeado Novo',
            '290' => 'Lima Campos',
            '291' => 'Loreto',
            '292' => 'Luis Domingues',
            '293' => 'Magalhaes de Almeida',
            '294' => 'Maracacume',
            '295' => 'Maraja do Sena',
            '296' => 'Maranhaozinho',
            '297' => 'Mata Roma',
            '298' => 'Matinha',
            '299' => 'Matoes do Norte',
            '300' => 'Matoes',
            '301' => 'Milagres do Maranhao',
            '302' => 'Mirador',
            '303' => 'Miranda do Norte',
            '304' => 'Mirinzal',
            '305' => 'Moncao',
            '306' => 'Montes Altos',
            '307' => 'Morros',
            '308' => 'Nina Rodrigues',
            '309' => 'Nova Colinas',
            '310' => 'Nova Iorque',
            '311' => 'Nova Olinda do Maranhao',
            '312' => 'Olho dAgua das Cunhas',
            '313' => 'Olinda Nova do Maranhao',
            '314' => 'Paco do Lumiar',
            '315' => 'Palmeirandia',
            '316' => 'Paraibano',
            '317' => 'Parnarama',
            '318' => 'Passagem Franca',
            '319' => 'Pastos Bons',
            '320' => 'Paulino Neves',
            '321' => 'Paulo Ramos',
            '322' => 'Pedreiras',
            '323' => 'Pedro do Rosario',
            '324' => 'Penalva',
            '325' => 'Peri Mirim',
            '326' => 'Peritoro',
            '327' => 'Pindare Mirim',
            '328' => 'Pinheiro',
            '329' => 'Pio XII',
            '330' => 'Pirapemas',
            '331' => 'Pocao de Pedras',
            '332' => 'Porto Franco',
            '333' => 'Porto Rico do Maranhao',
            '334' => 'Presidente Dutra',
            '335' => 'Presidente Juscelino',
            '336' => 'Presidente Medici',
            '337' => 'Presidente Sarney',
            '338' => 'Presidente Vargas',
            '339' => 'Primeira Cruz',
            '340' => 'Raposa',
            '341' => 'Riachao',
            '342' => 'Ribamar Fiquene',
            '343' => 'Rosario',
            '344' => 'Sambaiba',
            '345' => 'Santa Filomena do Maranhao',
            '346' => 'Santa Helena',
            '347' => 'Santa Ines',
            '348' => 'Santa Luzia do Parua',
            '349' => 'Santa Luzia',
            '350' => 'Santa Quiteria do Maranhao',
            '351' => 'Santa Rita',
            '352' => 'Santana do Maranhao',
            '353' => 'Santo Amaro do Maranhao',
            '354' => 'Santo Antonio dos Lopes',
            '355' => 'Sao Benedito do Rio Preto',
            '356' => 'Sao Bento',
            '357' => 'Sao Bernardo',
            '358' => 'Sao Domingos do Azeitao',
            '359' => 'Sao Domingos do Maranhao',
            '360' => 'Sao Felix de Balsas',
            '361' => 'Sao Francisco do Brejao',
            '362' => 'Sao Francisco do Maranhao',
            '363' => 'Sao Joao Batista',
            '364' => 'Sao Joao do Caru',
            '365' => 'Sao Joao do Paraiso',
            '366' => 'Sao Joao do Soter',
            '367' => 'Sao Joao dos Patos',
            '368' => 'Sao Jose de Ribamar',
            '369' => 'Sao Jose dos Basilios',
            '370' => 'Sao Luis Gonzaga do Maranhao',
            '371' => 'Sao Luis',
            '372' => 'Sao Mateus do Maranhao',
            '373' => 'Sao Pedro da Agua Branca',
            '374' => 'Sao Pedro dos Crentes',
            '375' => 'Sao Raimundo das Mangabeiras',
            '376' => 'Sao Raimundo do Doca Bezerra',
            '377' => 'Sao Roberto',
            '378' => 'Sao Vicente Ferrer',
            '379' => 'Satubinha',
            '380' => 'Senador Alexandre Costa',
            '381' => 'Senador La Rocque',
            '382' => 'Serrano do Maranhao',
            '383' => 'Sitio Novo',
            '384' => 'Sucupira do Norte',
            '385' => 'Sucupira do Riachao',
            '386' => 'Tasso Fragoso',
            '387' => 'Timbiras',
            '388' => 'Timon',
            '389' => 'Trizidela do Vale',
            '390' => 'Tufilandia',
            '391' => 'Tuntum',
            '392' => 'Turiacu',
            '393' => 'Turilandia',
            '394' => 'Tutoia',
            '395' => 'Urbano Santos',
            '396' => 'Vargem Grande',
            '397' => 'Viana',
            '398' => 'Vila Nova dos Martirios',
            '399' => 'Vitoria do Mearim',
            '400' => 'Vitorino Freire',
            '401' => 'Ze Doca',
        ];

        $cidadesPiaui = [
            '402' => 'Acaua',
            '403' => 'Agricolandia',
            '404' => 'Agua Branca',
            '405' => 'Alagoinha do Piaui',
            '406' => 'Alegrete do Piaui',
            '407' => 'Alto Longa',
            '408' => 'Altos',
            '409' => 'Alvorada do Gurgueia',
            '410' => 'Amarante',
            '411' => 'Angical do Piaui',
            '412' => 'Anisio de Abreu',
            '413' => 'Antonio Almeida',
            '414' => 'Aroazes',
            '415' => 'Arraial',
            '416' => 'Assuncao do Piaui',
            '417' => 'Avelino Lopes',
            '418' => 'Baixa Grande do Ribeiro',
            '419' => 'Barra dAlcantara',
            '420' => 'Barras',
            '421' => 'Barreiras do Piaui',
            '422' => 'Barro Duro',
            '423' => 'Batalha',
            '424' => 'Bela Vista do Piaui',
            '425' => 'Belem do Piaui',
            '426' => 'Beneditinos',
            '427' => 'Bertolinia',
            '428' => 'Betania do Piaui',
            '429' => 'Boa Hora',
            '430' => 'Bocaina',
            '431' => 'Bom Jesus',
            '432' => 'Bom Principio do Piaui',
            '433' => 'Bonfim do Piaui',
            '434' => 'Boqueirao do Piaui',
            '435' => 'Brasileira',
            '436' => 'Brejo do Piaui',
            '437' => 'Buriti dos Lopes',
            '438' => 'Buriti dos Montes',
            '439' => 'Cabeceiras do Piaui',
            '440' => 'Cajazeiras do Piaui',
            '441' => 'Cajueiro da Praia',
            '442' => 'Caldeirao Grande do Piaui',
            '443' => 'Campinas do Piaui',
            '444' => 'Campo Alegre do Fidalgo',
            '445' => 'Campo Grande do Piaui',
            '446' => 'Campo Largo do Piaui',
            '447' => 'Campo Maior',
            '448' => 'Canavieira',
            '449' => 'Canto do Buriti',
            '450' => 'Capitao Gervasio Oliveira',
            '451' => 'Capitao de Campos',
            '452' => 'Caracol',
            '453' => 'Caraubas do Piaui',
            '454' => 'Caridade do Piaui',
            '455' => 'Castelo do Piaui',
            '456' => 'Caxingo',
            '457' => 'Cocal de Telha',
            '458' => 'Cocal dos Alves',
            '459' => 'Cocal',
            '460' => 'Coivaras',
            '461' => 'Colonia do Gurgueia',
            '462' => 'Colonia do Piaui',
            '463' => 'Conceicao do Caninde',
            '464' => 'Coronel Jose Dias',
            '465' => 'Corrente',
            '466' => 'Cristalandia do Piaui',
            '467' => 'Cristino Castro',
            '468' => 'Curimata',
            '469' => 'Currais',
            '470' => 'Curral Novo do Piaui',
            '471' => 'Curralinhos',
            '472' => 'Demerval Lobao',
            '473' => 'Dirceu Arcoverde',
            '474' => 'Dom Expedito Lopes',
            '475' => 'Dom Inocencio',
            '476' => 'Domingos Mourao',
            '477' => 'Elesbao Veloso',
            '478' => 'Eliseu Martins',
            '479' => 'Esperantina',
            '480' => 'Fartura do Piaui',
            '481' => 'Flores do Piaui',
            '482' => 'Floresta do Piaui',
            '483' => 'Floriano',
            '484' => 'Francinopolis',
            '485' => 'Francisco Ayres',
            '486' => 'Francisco Macedo',
            '487' => 'Francisco Santos',
            '488' => 'Fronteiras',
            '489' => 'Geminiano',
            '490' => 'Gilbues',
            '491' => 'Guadalupe',
            '492' => 'Guaribas',
            '493' => 'Hugo Napoleao',
            '494' => 'Ilha Grande',
            '495' => 'Inhuma',
            '496' => 'Ipiranga do Piaui',
            '497' => 'Isaias Coelho',
            '498' => 'Itainopolis',
            '499' => 'Itaueira',
            '500' => 'Jacobina do Piaui',
            '501' => 'Jaicos',
            '502' => 'Jardim do Mulato',
            '503' => 'Jatoba do Piaui',
            '504' => 'Jerumenha',
            '505' => 'Joao Costa',
            '506' => 'Joaquim Pires',
            '507' => 'Joca Marques',
            '508' => 'Jose de Freitas',
            '509' => 'Juazeiro do Piaui',
            '510' => 'Julio Borges',
            '511' => 'Jurema',
            '512' => 'Lagoa Alegre',
            '513' => 'Lagoa de Sao Francisco',
            '514' => 'Lagoa do Barro do Piaui',
            '515' => 'Lagoa do Piaui',
            '516' => 'Lagoa do Sitio',
            '517' => 'Lagoinha do Piaui',
            '518' => 'Landri Sales',
            '519' => 'Luis Correia',
            '520' => 'Luzilandia',
            '521' => 'Madeiro',
            '522' => 'Manoel Emidio',
            '523' => 'Marcolandia',
            '524' => 'Marcos Parente',
            '525' => 'Massape do Piaui',
            '526' => 'Matias Olimpio',
            '527' => 'Miguel Alves',
            '528' => 'Miguel Leao',
            '529' => 'Milton Brandao',
            '530' => 'Monsenhor Gil',
            '531' => 'Monsenhor Hipolito',
            '532' => 'Monte Alegre do Piaui',
            '533' => 'Morro Cabeca no Tempo',
            '534' => 'Morro do Chapeu do Piaui',
            '535' => 'Murici dos Portelas',
            '536' => 'Nazare do Piaui',
            '537' => 'Nossa Senhora de Nazare',
            '538' => 'Nossa Senhora dos Remedios',
            '539' => 'Nova Santa Rita',
            '540' => 'Novo Oriente do Piaui',
            '541' => 'Novo Santo Antonio',
            '542' => 'Oeiras',
            '543' => 'Olho dAgua do Piaui',
            '544' => 'Padre Marcos',
            '545' => 'Paes Landim',
            '546' => 'Pajeu do Piaui',
            '547' => 'Palmeira do Piaui',
            '548' => 'Palmeirais',
            '549' => 'Paqueta',
            '550' => 'Parnagua',
            '551' => 'Parnaiba',
            '552' => 'Passagem Franca do Piaui',
            '553' => 'Patos do Piaui',
            '554' => 'Paulistana',
            '555' => 'Pavussu',
            '556' => 'Pedro II',
            '557' => 'Pedro Laurentino',
            '558' => 'Picos',
            '559' => 'Pimenteiras',
            '560' => 'Pio IX',
            '561' => 'Piracuruca',
            '562' => 'Piripiri',
            '563' => 'Porto Alegre do Piaui',
            '564' => 'Porto',
            '565' => 'Prata do Piaui',
            '566' => 'Queimada Nova',
            '567' => 'Redencao do Gurgueia',
            '568' => 'Regeneracao',
            '569' => 'Riacho Frio',
            '570' => 'Ribeira do Piaui',
            '571' => 'Ribeiro Goncalves',
            '572' => 'Rio Grande do Piaui',
            '573' => 'Santa Cruz do Piaui',
            '574' => 'Santa Cruz dos Milagres',
            '575' => 'Santa Filomena',
            '576' => 'Santa Luz',
            '577' => 'Santa Rosa do Piaui',
            '578' => 'Santana do Piaui',
            '579' => 'Santo Antonio de Lisboa',
            '580' => 'Santo Antonio dos Milagres',
            '581' => 'Santo Inacio do Piaui',
            '582' => 'Sao Braz do Piaui',
            '583' => 'Sao Felix do Piaui',
            '584' => 'Sao Francisco de Assis do Piaui',
            '585' => 'Sao Francisco do Piaui',
            '586' => 'Sao Goncalo do Gurgueia',
            '587' => 'Sao Goncalo do Piaui',
            '588' => 'Sao Joao da Canabrava',
            '589' => 'Sao Joao da Fronteira',
            '590' => 'Sao Joao da Serra',
            '591' => 'Sao Joao da Varjota',
            '592' => 'Sao Joao do Arraial',
            '593' => 'Sao Joao do Piaui',
            '594' => 'Sao Jose do Divino',
            '595' => 'Sao Jose do Peixe',
            '596' => 'Sao Jose do Piaui',
            '597' => 'Sao Juliao',
            '598' => 'Sao Lourenco do Piaui',
            '599' => 'Sao Luis do Piaui',
            '600' => 'Sao Miguel da Baixa Grande',
            '601' => 'Sao Miguel do Fidalgo',
            '602' => 'Sao Miguel do Tapuio',
            '603' => 'Sao Pedro do Piaui',
            '604' => 'Sao Raimundo Nonato',
            '605' => 'Sebastiao Barros',
            '606' => 'Sebastiao Leal',
            '607' => 'Sigefredo Pacheco',
            '608' => 'Simoes',
            '609' => 'Simplicio Mendes',
            '610' => 'Socorro do Piaui',
            '611' => 'Sussuapara',
            '612' => 'Tamboril do Piaui',
            '613' => 'Tanque do Piaui',
            '614' => 'Teresina',
            '615' => 'Uniao',
            '616' => 'Urucui',
            '617' => 'Valenca do Piaui',
            '618' => 'Varzea Branca',
            '619' => 'Varzea Grande',
            '620' => 'Vera Mendes',
            '621' => 'Vila Nova do Piaui',
            '622' => 'Wall Ferraz',
        ];

        $cidadesRioGrandeDoNorte = [
            '623' => 'Acari',
            '624' => 'Acu',
            '625' => 'Afonso Bezerra',
            '626' => 'Agua Nova',
            '627' => 'Alexandria',
            '628' => 'Almino Afonso',
            '629' => 'Alto do Rodrigues',
            '630' => 'Angicos',
            '631' => 'Antonio Martins',
            '632' => 'Apodi',
            '633' => 'Areia Branca',
            '634' => 'Ares',
            '635' => 'Augusto Severo',
            '636' => 'Baia Formosa',
            '637' => 'Barauna',
            '638' => 'Barcelona',
            '639' => 'Bento Fernandes',
            '640' => 'Bodo',
            '641' => 'Bom Jesus',
            '642' => 'Brejinho',
            '643' => 'Caicara do Norte',
            '644' => 'Caicara do Rio do Vento',
            '645' => 'Caico',
            '646' => 'Campo Redondo',
            '647' => 'Canguaretama',
            '648' => 'Caraubas',
            '649' => 'Carnauba dos Dantas',
            '650' => 'Carnaubais',
            '651' => 'Ceara-Mirim',
            '652' => 'Cerro Cora',
            '653' => 'Coronel Ezequiel',
            '654' => 'Coronel Joao Pessoa',
            '655' => 'Cruzeta',
            '656' => 'Currais Novos',
            '657' => 'Doutor Severiano',
            '658' => 'Encanto',
            '659' => 'Equador',
            '660' => 'Espirito Santo',
            '661' => 'Extremoz',
            '662' => 'Felipe Guerra',
            '663' => 'Fernando Pedroza',
            '664' => 'Florania',
            '665' => 'Francisco Dantas',
            '666' => 'Frutuoso Gomes',
            '667' => 'Galinhos',
            '668' => 'Goianinha',
            '669' => 'Governador Dix-Sept Rosado',
            '670' => 'Grossos',
            '671' => 'Guamare',
            '672' => 'Ielmo Marinho',
            '673' => 'Ipanguacu',
            '674' => 'Ipueira',
            '675' => 'Itaja',
            '676' => 'Itau',
            '677' => 'Jacana',
            '678' => 'Jandaira',
            '679' => 'Janduis',
            '680' => 'Januario Cicco',
            '681' => 'Japi',
            '682' => 'Jardim de Angicos',
            '683' => 'Jardim de Piranhas',
            '684' => 'Jardim do Serido',
            '685' => 'Joao Camara',
            '686' => 'Joao Dias',
            '687' => 'Jose da Penha',
            '688' => 'Jucurutu',
            '689' => 'Lagoa Nova',
            '690' => 'Lagoa Salgada',
            '691' => 'Lagoa dAnta',
            '692' => 'Lagoa de Pedras',
            '693' => 'Lagoa de Velhos',
            '694' => 'Lajes Pintadas',
            '695' => 'Lajes',
            '696' => 'Lucrecia',
            '697' => 'Luis Gomes',
            '698' => 'Macaiba',
            '699' => 'Macau',
            '700' => 'Major Sales',
            '701' => 'Marcelino Vieira',
            '702' => 'Martins',
            '703' => 'Maxaranguape',
            '704' => 'Messias Targino',
            '705' => 'Montanhas',
            '706' => 'Monte Alegre',
            '707' => 'Monte das Gameleiras',
            '708' => 'Mossoro',
            '709' => 'Natal',
            '710' => 'Nisia Floresta',
            '711' => 'Nova Cruz',
            '712' => 'Olho-dAgua do Borges',
            '713' => 'Ouro Branco',
            '714' => 'Parana',
            '715' => 'Parau',
            '716' => 'Parazinho',
            '717' => 'Parelhas',
            '718' => 'Parnamirim',
            '719' => 'Passa e Fica',
            '720' => 'Passagem',
            '721' => 'Patu',
            '722'=> 'Pau dos Ferros',
            '723'=> 'Pedra Grande',
            '724'=> 'Pedra Preta',
            '725'=> 'Pedro Avelino',
            '726'=> 'Pedro Velho',
            '727'=> 'Pendencias',
            '728'=> 'Piloes',
            '729'=> 'Poco Branco',
            '730'=> 'Portalegre',
            '731'=> 'Porto do Mangue',
            '732'=> 'Presidente Juscelino',
            '733'=> 'Pureza',
            '734'=> 'Rafael Fernandes',
            '735'=> 'Rafael Godeiro',
            '736'=> 'Riacho da Cruz',
            '737'=> 'Riacho de Santana',
            '738'=> 'Riachuelo',
            '739'=> 'Rio do Fogo',
            '740'=> 'Rodolfo Fernandes',
            '741'=> 'Ruy Barbosa',
            '742'=> 'Santa Cruz',
            '743'=> 'Santa Maria',
            '744'=> 'Santana do Matos',
            '745'=> 'Santana do Serido',
            '746'=> 'Santo Antonio',
            '747'=> 'Sao Bento do Norte',
            '748'=> 'Sao Bento do Trairi',
            '749'=> 'Sao Fernando',
            '750'=> 'Sao Francisco do Oeste',
            '751'=> 'Sao Goncalo do Amarante',
            '752'=> 'Sao Joao do Sabugi',
            '753'=> 'Sao Jose de Mipibu',
            '754'=> 'Sao Jose do Campestre',
            '755'=> 'Sao Jose do Serido',
            '756'=> 'Sao Miguel de Touros',
            '757'=> 'Sao Miguel',
            '758'=> 'Sao Paulo do Potengi',
            '759'=> 'Sao Pedro',
            '760'=> 'Sao Rafael',
            '761'=> 'Sao Tome',
            '762'=> 'Sao Vicente',
            '763'=> 'Senador Eloi de Souza',
            '764'=> 'Senador Georgino Avelino',
            '765'=> 'Serra Negra do Norte',
            '766'=> 'Serra de Sao Bento',
            '767'=> 'Serra do Mel',
            '768'=> 'Serrinha dos Pintos',
            '769'=> 'Serrinha',
            '770'=> 'Severiano Melo',
            '771'=> 'Sitio Novo',
            '772'=> 'Taboleiro Grande',
            '773'=> 'Taipu',
            '774'=> 'Tangara',
            '775'=> 'Tenente Ananias',
            '776'=> 'Tenente Laurentino Cruz',
            '777'=> 'Tibau do Sul',
            '778'=> 'Tibau',
            '779'=> 'Timbauba dos Batistas',
            '780'=> 'Touros',
            '781'=> 'Triunfo Potiguar',
            '782'=> 'Umarizal',
            '783'=> 'Upanema',
            '784'=> 'Varzea',
            '785'=> 'Venha-Ver',
            '786'=> 'Vera Cruz',
            '787'=> 'Vicosa',
            '788'=> 'Vila Flor',
        ];

        DB::table('users')->insert([
            'name' => 'Max',
            'email' => 'teste@teste.com.br',
            'password' => Hash::make('123456'),
        ]);
        // Estados
        foreach($states as $key => $s) {
            DB::table('state')->insert([
                'name' => $states[$key],
                'pais' => 'Brasil',
            ]);
        }

        // Cidades Ceará
        foreach($cidadesCeara as $key => $c) {
            DB::table('city')->insert([
                'name' => $cidadesCeara[$key],
                'state_id' => 1,
            ]);
        }

        // Cidades Maranhão
        foreach($cidadesMaranhao as $key => $c) {
            DB::table('city')->insert([
                'name' => $cidadesMaranhao[$key],
                'state_id' => 2,
            ]);
        }

        // Cidades Piaui
        foreach($cidadesPiaui as $key => $c) {
            DB::table('city')->insert([
                'name' => $cidadesPiaui[$key],
                'state_id' => 3,
            ]);
        }
        

        // Cidades RioGrandeDoNorte
        foreach($cidadesRioGrandeDoNorte as $key => $c) {
            DB::table('city')->insert([
                'name' => $cidadesRioGrandeDoNorte[$key],
                'state_id' => 4,
            ]);
        }

        $listStore = [
            [
                'brand_id' => 1,
                'address' => 'RUA:DR.JOÃO PESSOA, 618 A CENTRO',
                'information' => '(88) 3581-6699',
                'city_id' => '77',
                'lat' => -6.360161,
                'lng' => -39.299175,
            ],
            [
                'brand_id' => 1,
                'address' => 'AV PROFESSOR CARLOS CUNHA, 1000 LOJA 129',
                'information' => '(98) 3581-3650',
                'city_id' => '371',
                'lat' => -2.5090419,
                'lng' => -44.2864985,
            ],
            [
                'brand_id' => 1,
                'address' => 'AV DANIEL DE LA TOUCHE, 987 LOJA 320 G',
                'information' => '(86) 3230-2228',
                'city_id' => '371',
                'lat' => -2.5165253,
                'lng' => -44.2464014,
            ],
            [
                'brand_id' => 1,
                'address' => 'AV ININGA, 1201 LOJA V 122 - JOQUEI CLUB',
                'information' => '(98) 3259-3069',
                'city_id' => '614',
                'lat' => -5.0714409,
                'lng' => -42.7956896,
            ],
            [
                'brand_id' => 1,
                'address' => 'AV RAUL LOPES, 1000 LOJA 206',
                'information' => '(86) 3232-1994',
                'city_id' => '614',
                'lat' => -5.0824988,
                'lng' => -42.7928752,
            ],
            [
                'brand_id' => 1,
                'address' => 'AV NOSSA SENHORA DE FATIMA, 680',
                'information' => '(86) 3232-7832',
                'city_id' => '614',
                'lat' => -5.0700764,
                'lng' => -42.7920234,
            ],
            [
                'brand_id' => 1,
                'address' => 'AV MARECHAL CASTELO BRANCO, 911 LOJA 211',
                'information' => '(86) 31225236',
                'city_id' => '614',
                'lat' => -5.0953179,
                'lng' => -42.7890252,
            ],
            [
                'brand_id' => 2,
                'address' => 'RUA: FLORIANO PEIXOTO, 506 CENTRO',
                'information' => '(88) 98841-3457',
                'city_id' => '77',
                'lat' => -6.3602497,
                'lng' => -39.2976246,
            ],
            [
                'brand_id' => 2,
                'address' => 'RUA SANTA LUZIA, 328 CENTRO',
                'information' => '(88) 3512-1197',
                'city_id' => '99',
                'lat' => -7.2059349,
                'lng' => -39.3134128,
            ],
            [
                'brand_id' => 3,
                'address' => 'AV WASHINGTON SOARES, 85 LOJA 212',
                'information' => '(85) 3111-8115',
                'city_id' => '59',
                'lat' => -3.755786,
                'lng' => -38.4885943,
            ],
            [
                'brand_id' => 3,
                'address' => 'DESEMBARGADOR LAURO NOGUEIRA, 1500',
                'information' => '(85) 3636-0360',
                'city_id' => '59',
                'lat' => -3.7404008,
                'lng' => -38.4772423,
            ],
            [
                'brand_id' => 3,
                'address' => 'AV DANIEL DE LA TOUCHE, 987 LOJA 301 L',
                'information' => '(98) 3311-8234',
                'city_id' => '371',
                'lat' => -2.5165253,
                'lng' => -44.2464014,
            ],
            [
                'brand_id' => 4,
                'address' => 'RUA:DR.JOÃO PESSOA, 618  B CENTRO',
                'information' => '(88) 3581-0420',
                'city_id' => '77',
                'lat' => -6.3603391,
                'lng' => -39.2989778,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:RODRIGUES JUNIOR, 1227, CENTRO',
                'information' => '(88) 3412-1117',
                'city_id' => '149',
                'lat' => -14.2350040,
                'lng' => -51.9252800,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:MONSENHOR SALVIANO PINTO, 407A',
                'information' => '(88) 3441-3747',
                'city_id' => '151',
                'lat' => -5.198551,
                'lng' => -39.294695,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:Fº GURGEL VALENTE, 182',
                'information' => '(88) 3565-0905',
                'city_id' => '4',
                'lat' => -6.096350,
                'lng' => -39.455107,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:QUEIROZ PESSOA, 86',
                'information' => '(88) 3426-1274',
                'city_id' => '22',
                'lat' => -5.306438,
                'lng' => -38.920132,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA: NELSINHO LEAL, 71 CENTRO',
                'information' => '(88) 3517-1180',
                'city_id' => '100',
                'lat' => -6.524760,
                'lng' => -39.526468,
            ],
            [
                'brand_id' => 5,
                'address' => 'AV. DOS QUIXELOS, SUPER LAGOA',
                'information' => '(88) 98841-3226',
                'city_id' => '77',
                'lat' => -6.3549815,
                'lng' => -39.3067634,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:ANT.PEDRO BENEVIDES, 42',
                'information' => '(88) 3583-1701',
                'city_id' => '115',
                'lat' => -5.743056,
                'lng' => -39.627717,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:SANTA ROSA, 24',
                'information' => '(88) 3448-2157',
                'city_id' => '135',
                'lat' => -6.004548,
                'lng' => -40.293331,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA: PROF. JOÃO COELHO, 31, CENTRO',
                'information' => '(88) 3581-2912',
                'city_id' => '77',
                'lat' => -6.3609164,
                'lng' => -39.3009249,
            ],
            [
                'brand_id' => 5,
                'address' => 'PRAÇA HENRIQUE ANDRADE, 13 CENTRO',
                'information' => '(88) 3437-3446',
                'city_id' => '172',
                'lat' => -6.003368,
                'lng' => -40.294051,
            ],
            [
                'brand_id' => 5,
                'address' => 'AV.Fº FRANÇA CAMBRAIA, 279',
                'information' => '(88) 3449-0080',
                'city_id' => '165',
                'lat' => -5.588556,
                'lng' => -39.372360,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:MONSENHOR MACEDO, 146A',
                'information' => '(88) 3536-2134',
                'city_id' => '101',
                'lat' => -6.749104,
                'lng' => -38.964694,
            ],
            [
                'brand_id' => 5,
                'address' => 'AV: CARLOS ROBERTO COSTA, 334',
                'information' => '(88) 3581-5577',
                'city_id' => '77',
                'lat' => -6.3587958,
                'lng' => -39.2980590,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:DONDON FEITOSA, 73',
                'information' => '(88) 3437-2246',
                'city_id' => '172',
                'lat' => -6.003358,
                'lng' => -40.294028,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA: EPITACIO PESSOA, 122 CENTRO',
                'information' => '(88) 3581-3243',
                'city_id' => '77',
                'lat' => -6.3619642,
                'lng' => -39.2979761,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA: ELICIO ABREU, 23',
                'information' => '(88) 3515-1810',
                'city_id' => '137',
                'lat' => -5.454019,
                'lng' => -39.714618,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:DUQUE DE CAXIAS, 30',
                'information' => '(88) 3541-1659',
                'city_id' => '183',
                'lat' => -6.794381,
                'lng' => -39.298252,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:DEOCLECIANO ARAGÃO, 154 CENTRO',
                'information' => '(88) 3629-3052',
                'city_id' => '124',
                'lat' => -5.536287,
                'lng' => -40.776417,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA DR. RUI MAIA, 541 CENTRO',
                'information' => '(88) 3412-1062',
                'city_id' => '149',
                'lat' => -14.2350040,
                'lng' => -51.9252800,
            ],
            [
                'brand_id' => 5,
                'address' => 'AV.NOGUEIRA ACIOLY, 1310',
                'information' => '(88) 3561-1834',
                'city_id' => '76',
                'lat' => -6.402781,
                'lng' => -38.860619,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:DR.PAULO RAMOS, 936 CENTRO',
                'information' => '(98) 3478-1307',
                'city_id' => '200',
                'lat' => -2.886439,
                'lng' => -41.904539,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA: BARÃO DO RIO BRANCO, 604 B',
                'information' => '(98) 3477-1483',
                'city_id' => '357',
                'lat' => -3.370785,
                'lng' => -42.418642,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA: BARÃO DO RIO BRANCO, 604 A',
                'information' => '(98) 3477-1483',
                'city_id' => '357',
                'lat' => -3.370785,
                'lng' => -42.418642,
            ],
            [
                'brand_id' => 5,
                'address' => 'PRAÇA DA GRAÇA, 745 A',
                'information' => '(86) 3321-2420',
                'city_id' => '551',
                'lat' => -7.7183401,
                'lng' => -42.7289236,
            ],
            [
                'brand_id' => 5,
                'address' => 'AV.DEP. PINHEIRO MACHADO, 1397 SL 101',
                'information' => '(86) 3322-5749',
                'city_id' => '551',
                'lat' => -2.9211801,
                'lng' => -41.7542423,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:CORONEL JOSÉ NARCISIO',
                'information' => '(86) 3321-2775',
                'city_id' => '551',
                'lat' => -2.9045169,
                'lng' => -41.7775605,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA:ANT. DAMASCENO, 03 CENTRO',
                'information' => '(86) 3362-1313',
                'city_id' => '459',
                'lat' => -3.470112,
                'lng' => -41.557418,
            ],
            [
                'brand_id' => 5,
                'address' => 'AV: SENADOR JOAQUIM PIRES, 1043',
                'information' => '(86) 3367-1320',
                'city_id' => '519',
                'lat' => -2.881552,
                'lng' => -41.657143,
            ],
            [
                'brand_id' => 5,
                'address' => 'AV: SÃO SEBASTIÃO, 3429',
                'information' => '(86) 3323-3846',
                'city_id' => '551',
                'lat' => -2.9106475,
                'lng' => -41.7325683,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA FELIPE GUERRA, 334',
                'information' => '(84) 3417-1817',
                'city_id' => '645',
                'lat' => -6.458628,
                'lng' => -37.094883,
            ],
            [
                'brand_id' => 5,
                'address' => 'AV CORONEL MATINIANO, 414',
                'information' => '(84) 3417-1817',
                'city_id' => '645',
                'lat' => -6.458750,
                'lng' => -37.097747,
            ],
            [
                'brand_id' => 5,
                'address' => 'AV CORONEL MATINIANO, 970',
                'information' => '(84) 3417-2429',
                'city_id' => '645',
                'lat' => -6.462308,
                'lng' => -37.094037,
            ],
            [
                'brand_id' => 5,
                'address' => 'RUA DR GEVACY DE FREITAS, 27',
                'information' => '(84) 3417-1817',
                'city_id' => '683',
                'lat' => -6.380423,
                'lng' => -37.350996,
            ],
            [
                'brand_id' => 5,
                'address' => 'PRAÇA JANUNCIO AFONSO DE MEDEIROS, 29',
                'information' => '(84) 3429-2458',
                'city_id' => '688',
                'lat' => -6.042687,
                'lng' => -37.025894,
            ],
            [
                'brand_id' => 6,
                'address' => 'RUA: FLORIANO PEIXOTO, 526',
                'information' => '(88) 3581-4134',
                'city_id' => '77',
                'lat' => -6.3602497,
                'lng' => -39.2976246,
            ],
        ];                   
        
        $brands = [
            ['id' => 1, 'name' => 'AREZZO', 'image' => 'icons/arezzo.png'], // 1
            ['id' => 2, 'name' => 'CACAU SHOW', 'image' => 'icons/cacau-show.png'], // 2
            ['id' => 3, 'name' => 'CROCS', 'image' => 'icons/crocs.png'], // 3
            ['id' => 4, 'name' => 'MAGRELLA', 'image' => 'icons/magrella.png'], // 4
            ['id' => 5, 'name' => 'O BOTICARIO', 'image' => 'icons/boticario.png'], // 5
            ['id' => 6, 'name' => 'TIM', 'image' => 'icons/tim.png'], // 6
        ];

        foreach($brands as $b) {
            DB::table('brand')->insert([
                'name' => $b['name'],
                'image' => $b['image'],
            ]);
        }

        foreach($listStore as $store) {
            DB::table('store')->insert([
                'brand_id' => $store['brand_id'],
                'address' => $store['address'],
                'information' => $store['information'],
                'city_id' => $store['city_id'],
                'lat' => $store['lat'],
                'lng' => $store['lng'],
            ]);
        }

        DB::table('jobs_employment')->insert([
            'title' => 'Banco de Talentos',
            'description' => 'Banco de Talentos',
            'status' => 0,
            'date_begin' => '2020-01-01',
            'city_id' => 1,
        ]);
    }
}
