<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {

        $states = [
            '1' => 'Ceará',
            '2' => 'Maranhão',
            '3' => 'Piauí'
        ];

        $cidadesCeara = [
            '1' => 'Abaiara',
            '2' => 'Acarape',
            '3' => 'Acarau',
            '4' => 'Acopiara',
            '5' => 'Aiuaba',
            '6' => 'Alcantaras',
            '7' => 'Altaneira',
            '8' => 'Alto Santo',
            '9' => 'Amontada',
            '10' => 'Antonina do Norte',
            '11' => 'Apuiares',
            '12' => 'Aquiraz',
            '13' => 'Aracati',
            '14' => 'Aracoiaba',
            '15' => 'Ararenda',
            '16' => 'Araripe',
            '17' => 'Aratuba',
            '18' => 'Arneiroz',
            '19' => 'Assare',
            '20' => 'Aurora',
            '21' => 'Baixio',
            '22' => 'Banabuiu',
            '23' => 'Barbalha',
            '24' => 'Barreira',
            '25' => 'Barro',
            '26' => 'Barroquinha',
            '27' => 'Baturite',
            '28' => 'Beberibe',
            '29' => 'Bela Cruz',
            '30' => 'Boa Viagem',
            '31' => 'Brejo Santo',
            '32' => 'Camocim',
            '33' => 'Campos Sales',
            '34' => 'Caninde',
            '35' => 'Capistrano',
            '36' => 'Caridade',
            '37' => 'Carire',
            '38' => 'Caririacu',
            '39' => 'Carius',
            '40' => 'Carnaubal',
            '41' => 'Cascavel',
            '42' => 'Catarina',
            '43' => 'Catunda',
            '44' => 'Caucaia',
            '45' => 'Cedro',
            '46' => 'Chaval',
            '47' => 'Choro',
            '48' => 'Chorozinho',
            '49' => 'Coreau',
            '50' => 'Crateus',
            '51' => 'Crato',
            '52' => 'Croata',
            '53' => 'Cruz',
            '54' => 'Deputado Irapuan Pinheiro',
            '55' => 'Erere',
            '56' => 'Eusebio',
            '57' => 'Farias Brito',
            '58' => 'Forquilha',
            '59' => 'Fortaleza',
            '60' => 'Fortim',
            '61' => 'Frecheirinha',
            '62' => 'General Sampaio',
            '63' => 'Graca',
            '64' => 'Granja',
            '65' => 'Granjeiro',
            '66' => 'Groairas',
            '67' => 'Guaiuba',
            '68' => 'Guaraciaba do Norte',
            '69' => 'Guaramiranga',
            '70' => 'Hidrolandia',
            '71' => 'Horizonte',
            '72' => 'Ibaretama',
            '73' => 'Ibiapina',
            '74' => 'Ibicuitinga',
            '75' => 'Icapui',
            '76' => 'Ico',
            '77' => 'Iguatu',
            '78' => 'Independencia',
            '79' => 'Ipaporanga',
            '80' => 'Ipaumirim',
            '81' => 'Ipu',
            '82' => 'Ipueiras',
            '83' => 'Iracema',
            '84' => 'Iraucuba',
            '85' => 'Itaicaba',
            '86' => 'Itaitinga',
            '87' => 'Itapage',
            '88' => 'Itapipoca',
            '89' => 'Itapiuna',
            '90' => 'Itarema',
            '91' => 'Itatira',
            '92' => 'Jaguaretama',
            '93' => 'Jaguaribara',
            '94' => 'Jaguaribe',
            '95' => 'Jaguaruana',
            '96' => 'Jardim',
            '97' => 'Jati',
            '98' => 'Jijoca de Jericoacoara',
            '99' => 'Juazeiro do Norte',
            '100' => 'Jucas',
            '101' => 'Lavras da Mangabeira',
            '102' => 'Limoeiro do Norte',
            '103' => 'Madalena',
            '104' => 'Maracanau',
            '105' => 'Maranguape',
            '106' => 'Marco',
            '107' => 'Martinopole',
            '108' => 'Massape',
            '109' => 'Mauriti',
            '110' => 'Meruoca',
            '111' => 'Milagres',
            '112' => 'Milha',
            '113' => 'Miraima',
            '114' => 'Missao Velha',
            '115' => 'Mombaca',
            '116' => 'Monsenhor Tabosa',
            '117' => 'Morada Nova',
            '118' => 'Moraujo',
            '119' => 'Morrinhos',
            '120' => 'Mucambo',
            '121' => 'Mulungu',
            '122' => 'Nova Olinda',
            '123' => 'Nova Russas',
            '124' => 'Novo Oriente',
            '125' => 'Ocara',
            '126' => 'Oros',
            '127' => 'Pacajus',
            '128' => 'Pacatuba',
            '129' => 'Pacoti',
            '130' => 'Pacuja',
            '131' => 'Palhano',
            '132' => 'Palmacia',
            '133' => 'Paracuru',
            '134' => 'Paraipaba',
            '135' => 'Parambu',
            '136' => 'Paramoti',
            '137' => 'Pedra Branca',
            '138' => 'Penaforte',
            '139' => 'Pentecoste',
            '140' => 'Pereiro',
            '141' => 'Pindoretama',
            '142' => 'Piquet Carneiro',
            '143' => 'Pires Ferreira',
            '144' => 'Poranga',
            '145' => 'Porteiras',
            '146' => 'Potengi',
            '147' => 'Potiretama',
            '148' => 'Quiterianopolis',
            '149' => 'Quixada',
            '150' => 'Quixela',
            '151' => 'Quixeramobim',
            '152' => 'Quixere',
            '153' => 'Redencao',
            '154' => 'Reriutaba',
            '155' => 'Russas',
            '156' => 'Saboeiro',
            '157' => 'Salitre',
            '158' => 'Santa Quiteria',
            '159' => 'Santana do Acarau',
            '160' => 'Santana do Cariri',
            '161' => 'Sao Benedito',
            '162' => 'Sao Goncalo do Amarante',
            '163' => 'Sao Joao do Jaguaribe',
            '164' => 'Sao Luis do Curu',
            '165' => 'Senador Pompeu',
            '166' => 'Senador Sa',
            '167' => 'Sobral',
            '168' => 'Solonopole',
            '169' => 'Tabuleiro do Norte',
            '170' => 'Tamboril',
            '171' => 'Tarrafas',
            '172' => 'Taua',
            '173' => 'Tejucuoca',
            '174' => 'Tiangua',
            '175' => 'Trairi',
            '176' => 'Tururu',
            '177' => 'Ubajara',
            '178' => 'Umari',
            '179' => 'Umirim',
            '180' => 'Uruburetama',
            '181' => 'Uruoca',
            '182' => 'Varjota',
            '183' => 'Varzea Alegre',
            '184' => 'Vicosa do Ceara',
        ];

        $cidadesMaranhao = [
            '1' => 'Acailandia',
            '2' => 'Afonso Cunha',
            '3' => 'Agua Doce do Maranhao',
            '4' => 'Alcantara',
            '5' => 'Aldeias Altas',
            '6' => 'Altamira do Maranhao',
            '7' => 'Alto Alegre do Maranhao',
            '8' => 'Alto Alegre do Pindare',
            '9' => 'Alto Parnaiba',
            '10' => 'Amapa do Maranhao',
            '11' => 'Amarante do Maranhao',
            '12' => 'Anajatuba',
            '13' => 'Anapurus',
            '14' => 'Apicum-Acu',
            '15' => 'Araguana',
            '16' => 'Araioses',
            '17' => 'Arame',
            '18' => 'Arari',
            '19' => 'Axixa',
            '20' => 'Bacabal',
            '21' => 'Bacabeira',
            '22' => 'Bacuri',
            '23' => 'Bacurituba',
            '24' => 'Balsas',
            '25' => 'Barao de Grajau',
            '26' => 'Barra do Corda',
            '27' => 'Barreirinhas',
            '28' => 'Bela Vista do Maranhao',
            '29' => 'Belagua',
            '30' => 'Benedito Leite',
            '31' => 'Bequimao',
            '32' => 'Bernardo do Mearim',
            '33' => 'Boa Vista do Gurupi',
            '34' => 'Bom Jardim',
            '35' => 'Bom Jesus das Selvas',
            '36' => 'Bom Lugar',
            '37' => 'Brejo de Areia',
            '38' => 'Brejo',
            '39' => 'Buriti Bravo',
            '40' => 'Buriti',
            '41' => 'Buriticupu',
            '42' => 'Buritirama',
            '43' => 'Cachoeira Grande',
            '44' => 'Cajapio',
            '45' => 'Cajari',
            '46' => 'Campestre do Maranhao',
            '47' => 'Candido Mendes',
            '48' => 'Cantanhede',
            '49' => 'Capinzal do Norte',
            '50' => 'Carolina',
            '51' => 'Carutapera',
            '52' => 'Caxias',
            '53' => 'Cedral',
            '54' => 'Central do Maranhao',
            '55' => 'Centro Novo do Maranhao',
            '56' => 'Centro do Guilherme',
            '57' => 'Chapadinha',
            '58' => 'Cidelandia',
            '59' => 'Codo',
            '60' => 'Coelho Neto',
            '61' => 'Colinas',
            '62' => 'Conceicao do Lago-Acu',
            '63' => 'Coroata',
            '64' => 'Cururupu',
            '65' => 'Davinopolis',
            '66' => 'Dom Pedro',
            '67' => 'Duque Bacelar',
            '68' => 'Esperantinopolis',
            '69' => 'Estreito',
            '70' => 'Feira Nova do Maranhao',
            '71' => 'Fernando Falcao',
            '72' => 'Formosa da Serra Negra',
            '73' => 'Fortaleza dos Nogueiras',
            '74' => 'Fortuna',
            '75' => 'Godofredo Viana',
            '76' => 'Goncalves Dias',
            '77' => 'Governador Archer',
            '78' => 'Governador Edison Lobao',
            '79' => 'Governador Eugenio Barros',
            '80' => 'Governador Luiz Rocha',
            '81' => 'Governador Newton Bello',
            '82' => 'Governador Nunes Freire',
            '83' => 'Graca Aranha',
            '84' => 'Grajau',
            '85' => 'Guimaraes',
            '86' => 'Humberto de Campos',
            '87' => 'Icatu',
            '88' => 'Igarape Grande',
            '89' => 'Igarape do Meio',
            '90' => 'Imperatriz',
            '91' => 'Itaipava do Grajau',
            '92' => 'Itapecuru Mirim',
            '93' => 'Itinga do Maranhao',
            '94' => 'Jatoba',
            '95' => 'Jenipapo dos Vieiras',
            '96' => 'Joao Lisboa',
            '97' => 'Joselandia',
            '98' => 'Junco do Maranhao',
            '99' => 'Lago Verde',
            '100' => 'Lago da Pedra',
            '101' => 'Lago do Junco',
            '102' => 'Lagoa Grande do Maranhao',
            '103' => 'Lagoa do Mato',
            '104' => 'Lagoa dos Rodrigues',
            '105' => 'Lajeado Novo',
            '106' => 'Lima Campos',
            '107' => 'Loreto',
            '108' => 'Luis Domingues',
            '109' => 'Magalhaes de Almeida',
            '110' => 'Maracacume',
            '111' => 'Maraja do Sena',
            '112' => 'Maranhaozinho',
            '113' => 'Mata Roma',
            '114' => 'Matinha',
            '115' => 'Matoes do Norte',
            '116' => 'Matoes',
            '117' => 'Milagres do Maranhao',
            '118' => 'Mirador',
            '119' => 'Miranda do Norte',
            '120' => 'Mirinzal',
            '121' => 'Moncao',
            '122' => 'Montes Altos',
            '123' => 'Morros',
            '124' => 'Nina Rodrigues',
            '125' => 'Nova Colinas',
            '126' => 'Nova Iorque',
            '127' => 'Nova Olinda do Maranhao',
            '128' => 'Olho dAgua das Cunhas',
            '129' => 'Olinda Nova do Maranhao',
            '130' => 'Paco do Lumiar',
            '131' => 'Palmeirandia',
            '132' => 'Paraibano',
            '133' => 'Parnarama',
            '134' => 'Passagem Franca',
            '135' => 'Pastos Bons',
            '136' => 'Paulino Neves',
            '137' => 'Paulo Ramos',
            '138' => 'Pedreiras',
            '139' => 'Pedro do Rosario',
            '140' => 'Penalva',
            '141' => 'Peri Mirim',
            '142' => 'Peritoro',
            '143' => 'Pindare Mirim',
            '144' => 'Pinheiro',
            '145' => 'Pio XII',
            '146' => 'Pirapemas',
            '147' => 'Pocao de Pedras',
            '148' => 'Porto Franco',
            '149' => 'Porto Rico do Maranhao',
            '150' => 'Presidente Dutra',
            '151' => 'Presidente Juscelino',
            '152' => 'Presidente Medici',
            '153' => 'Presidente Sarney',
            '154' => 'Presidente Vargas',
            '155' => 'Primeira Cruz',
            '156' => 'Raposa',
            '157' => 'Riachao',
            '158' => 'Ribamar Fiquene',
            '159' => 'Rosario',
            '160' => 'Sambaiba',
            '161' => 'Santa Filomena do Maranhao',
            '162' => 'Santa Helena',
            '163' => 'Santa Ines',
            '164' => 'Santa Luzia do Parua',
            '165' => 'Santa Luzia',
            '166' => 'Santa Quiteria do Maranhao',
            '167' => 'Santa Rita',
            '168' => 'Santana do Maranhao',
            '169' => 'Santo Amaro do Maranhao',
            '170' => 'Santo Antonio dos Lopes',
            '171' => 'Sao Benedito do Rio Preto',
            '172' => 'Sao Bento',
            '173' => 'Sao Bernardo',
            '174' => 'Sao Domingos do Azeitao',
            '175' => 'Sao Domingos do Maranhao',
            '176' => 'Sao Felix de Balsas',
            '177' => 'Sao Francisco do Brejao',
            '178' => 'Sao Francisco do Maranhao',
            '179' => 'Sao Joao Batista',
            '180' => 'Sao Joao do Caru',
            '181' => 'Sao Joao do Paraiso',
            '182' => 'Sao Joao do Soter',
            '183' => 'Sao Joao dos Patos',
            '184' => 'Sao Jose de Ribamar',
            '185' => 'Sao Jose dos Basilios',
            '186' => 'Sao Luis Gonzaga do Maranhao',
            '187' => 'Sao Luis',
            '188' => 'Sao Mateus do Maranhao',
            '189' => 'Sao Pedro da Agua Branca',
            '190' => 'Sao Pedro dos Crentes',
            '191' => 'Sao Raimundo das Mangabeiras',
            '192' => 'Sao Raimundo do Doca Bezerra',
            '193' => 'Sao Roberto',
            '194' => 'Sao Vicente Ferrer',
            '195' => 'Satubinha',
            '196' => 'Senador Alexandre Costa',
            '197' => 'Senador La Rocque',
            '198' => 'Serrano do Maranhao',
            '199' => 'Sitio Novo',
            '200' => 'Sucupira do Norte',
            '201' => ' Sucupira do Riachao',
            '202' => ' Tasso Fragoso',
            '203' => ' Timbiras',
            '204' => ' Timon',
            '205' => ' Trizidela do Vale',
            '206' => ' Tufilandia',
            '207' => ' Tuntum',
            '208' => ' Turiacu',
            '209' => ' Turilandia',
            '210' => ' Tutoia',
            '211' => ' Urbano Santos',
            '212' => ' Vargem Grande',
            '213' => ' Viana',
            '214' => ' Vila Nova dos Martirios',
            '215' => ' Vitoria do Mearim',
            '216' => ' Vitorino Freire',
            '217' => ' Ze Doca',
        ];

        $cidadesPiaui = [
            '1' => 'Acaua',
            '2' => 'Agricolandia',
            '3' => 'Agua Branca',
            '4' => 'Alagoinha do Piaui',
            '5' => 'Alegrete do Piaui',
            '6' => 'Alto Longa',
            '7' => 'Altos',
            '8' => 'Alvorada do Gurgueia',
            '9' => 'Amarante',
            '10' => 'Angical do Piaui',
            '11' => 'Anisio de Abreu',
            '12' => 'Antonio Almeida',
            '13' => 'Aroazes',
            '14' => 'Arraial',
            '15' => 'Assuncao do Piaui',
            '16' => 'Avelino Lopes',
            '17' => 'Baixa Grande do Ribeiro',
            '18' => 'Barra dAlcantara',
            '19' => 'Barras',
            '20' => 'Barreiras do Piaui',
            '21' => 'Barro Duro',
            '22' => 'Batalha',
            '23' => 'Bela Vista do Piaui',
            '24' => 'Belem do Piaui',
            '25' => 'Beneditinos',
            '26' => 'Bertolinia',
            '27' => 'Betania do Piaui',
            '28' => 'Boa Hora',
            '29' => 'Bocaina',
            '30' => 'Bom Jesus',
            '31' => 'Bom Principio do Piaui',
            '32' => 'Bonfim do Piaui',
            '33' => 'Boqueirao do Piaui',
            '34' => 'Brasileira',
            '35' => 'Brejo do Piaui',
            '36' => 'Buriti dos Lopes',
            '37' => 'Buriti dos Montes',
            '38' => 'Cabeceiras do Piaui',
            '39' => 'Cajazeiras do Piaui',
            '40' => 'Cajueiro da Praia',
            '41' => 'Caldeirao Grande do Piaui',
            '42' => 'Campinas do Piaui',
            '43' => 'Campo Alegre do Fidalgo',
            '44' => 'Campo Grande do Piaui',
            '45' => 'Campo Largo do Piaui',
            '46' => 'Campo Maior',
            '47' => 'Canavieira',
            '48' => 'Canto do Buriti',
            '49' => 'Capitao Gervasio Oliveira',
            '50' => 'Capitao de Campos',
            '51' => 'Caracol',
            '52' => 'Caraubas do Piaui',
            '53' => 'Caridade do Piaui',
            '54' => 'Castelo do Piaui',
            '55' => 'Caxingo',
            '56' => 'Cocal de Telha',
            '57' => 'Cocal dos Alves',
            '58' => 'Cocal',
            '59' => 'Coivaras',
            '60' => 'Colonia do Gurgueia',
            '61' => 'Colonia do Piaui',
            '62' => 'Conceicao do Caninde',
            '63' => 'Coronel Jose Dias',
            '64' => 'Corrente',
            '65' => 'Cristalandia do Piaui',
            '66' => 'Cristino Castro',
            '67' => 'Curimata',
            '68' => 'Currais',
            '69' => 'Curral Novo do Piaui',
            '70' => 'Curralinhos',
            '71' => 'Demerval Lobao',
            '72' => 'Dirceu Arcoverde',
            '73' => 'Dom Expedito Lopes',
            '74' => 'Dom Inocencio',
            '75' => 'Domingos Mourao',
            '76' => 'Elesbao Veloso',
            '77' => 'Eliseu Martins',
            '78' => 'Esperantina',
            '79' => 'Fartura do Piaui',
            '80' => 'Flores do Piaui',
            '81' => 'Floresta do Piaui',
            '82' => 'Floriano',
            '83' => 'Francinopolis',
            '84' => 'Francisco Ayres',
            '85' => 'Francisco Macedo',
            '86' => 'Francisco Santos',
            '87' => 'Fronteiras',
            '88' => 'Geminiano',
            '89' => 'Gilbues',
            '90' => 'Guadalupe',
            '91' => 'Guaribas',
            '92' => 'Hugo Napoleao',
            '93' => 'Ilha Grande',
            '94' => 'Inhuma',
            '95' => 'Ipiranga do Piaui',
            '96' => 'Isaias Coelho',
            '97' => 'Itainopolis',
            '98' => 'Itaueira',
            '99' => 'Jacobina do Piaui',
            '100' => 'Jaicos',
            '101' => 'Jardim do Mulato',
            '102' => 'Jatoba do Piaui',
            '103' => 'Jerumenha',
            '104' => 'Joao Costa',
            '105' => 'Joaquim Pires',
            '106' => 'Joca Marques',
            '107' => 'Jose de Freitas',
            '108' => 'Juazeiro do Piaui',
            '109' => 'Julio Borges',
            '110' => 'Jurema',
            '111' => 'Lagoa Alegre',
            '112' => 'Lagoa de Sao Francisco',
            '113' => 'Lagoa do Barro do Piaui',
            '114' => 'Lagoa do Piaui',
            '115' => 'Lagoa do Sitio',
            '116' => 'Lagoinha do Piaui',
            '117' => 'Landri Sales',
            '118' => 'Luis Correia',
            '119' => 'Luzilandia',
            '120' => 'Madeiro',
            '121' => 'Manoel Emidio',
            '122' => 'Marcolandia',
            '123' => 'Marcos Parente',
            '124' => 'Massape do Piaui',
            '125' => 'Matias Olimpio',
            '126' => 'Miguel Alves',
            '127' => 'Miguel Leao',
            '128' => 'Milton Brandao',
            '129' => 'Monsenhor Gil',
            '130' => 'Monsenhor Hipolito',
            '131' => 'Monte Alegre do Piaui',
            '132' => 'Morro Cabeca no Tempo',
            '133' => 'Morro do Chapeu do Piaui',
            '134' => 'Murici dos Portelas',
            '135' => 'Nazare do Piaui',
            '136' => 'Nossa Senhora de Nazare',
            '137' => 'Nossa Senhora dos Remedios',
            '138' => 'Nova Santa Rita',
            '139' => 'Novo Oriente do Piaui',
            '140' => 'Novo Santo Antonio',
            '141' => 'Oeiras',
            '142' => 'Olho dAgua do Piaui',
            '143' => 'Padre Marcos',
            '144' => 'Paes Landim',
            '145' => 'Pajeu do Piaui',
            '146' => 'Palmeira do Piaui',
            '147' => 'Palmeirais',
            '148' => 'Paqueta',
            '149' => 'Parnagua',
            '150' => 'Parnaiba',
            '151' => 'Passagem Franca do Piaui',
            '152' => 'Patos do Piaui',
            '153' => 'Paulistana',
            '154' => 'Pavussu',
            '155' => 'Pedro II',
            '156' => 'Pedro Laurentino',
            '157' => 'Picos',
            '158' => 'Pimenteiras',
            '159' => 'Pio IX',
            '160' => 'Piracuruca',
            '161' => 'Piripiri',
            '162' => 'Porto Alegre do Piaui',
            '163' => 'Porto',
            '164' => 'Prata do Piaui',
            '165' => 'Queimada Nova',
            '166' => 'Redencao do Gurgueia',
            '167' => 'Regeneracao',
            '168' => 'Riacho Frio',
            '169' => 'Ribeira do Piaui',
            '170' => 'Ribeiro Goncalves',
            '171' => 'Rio Grande do Piaui',
            '172' => 'Santa Cruz do Piaui',
            '173' => 'Santa Cruz dos Milagres',
            '174' => 'Santa Filomena',
            '175' => 'Santa Luz',
            '176' => 'Santa Rosa do Piaui',
            '177' => 'Santana do Piaui',
            '178' => 'Santo Antonio de Lisboa',
            '179' => 'Santo Antonio dos Milagres',
            '180' => 'Santo Inacio do Piaui',
            '181' => 'Sao Braz do Piaui',
            '182' => 'Sao Felix do Piaui',
            '183' => 'Sao Francisco de Assis do Piaui',
            '184' => 'Sao Francisco do Piaui',
            '185' => 'Sao Goncalo do Gurgueia',
            '186' => 'Sao Goncalo do Piaui',
            '187' => 'Sao Joao da Canabrava',
            '188' => 'Sao Joao da Fronteira',
            '189' => 'Sao Joao da Serra',
            '190' => 'Sao Joao da Varjota',
            '191' => 'Sao Joao do Arraial',
            '192' => 'Sao Joao do Piaui',
            '193' => 'Sao Jose do Divino',
            '194' => 'Sao Jose do Peixe',
            '195' => 'Sao Jose do Piaui',
            '196' => 'Sao Juliao',
            '197' => 'Sao Lourenco do Piaui',
            '198' => 'Sao Luis do Piaui',
            '199' => 'Sao Miguel da Baixa Grande',
            '200' => 'Sao Miguel do Fidalgo',
            '201' => 'Sao Miguel do Tapuio',
            '202' => 'Sao Pedro do Piaui',
            '203' => 'Sao Raimundo Nonato',
            '204' => 'Sebastiao Barros',
            '205' => 'Sebastiao Leal',
            '206' => 'Sigefredo Pacheco',
            '207' => 'Simoes',
            '208' => 'Simplicio Mendes',
            '209' => 'Socorro do Piaui',
            '210' => 'Sussuapara',
            '211' => 'Tamboril do Piaui',
            '212' => 'Tanque do Piaui',
            '213' => 'Teresina',
            '214' => 'Uniao',
            '215' => 'Urucui',
            '216' => 'Valenca do Piaui',
            '217' => 'Varzea Branca',
            '218' => 'Varzea Grande',
            '219' => 'Vera Mendes',
            '220' => 'Vila Nova do Piaui',
            '221' => 'Wall Ferraz',
        ];

        DB::table('users')->insert([
            'name' => 'Max',
            'email' => 'teste@teste.com.br',
            'password' => Hash::make('123456'),
        ]);
        // Estados
        foreach($states as $key => $s) {
            DB::table('state')->insert([
                'name' => $states[$key],
                'pais' => 'Brasil',
            ]);
        }

        // Cidades Ceará
        foreach($cidadesCeara as $key => $c) {
            DB::table('city')->insert([
                'name' => $cidadesCeara[$key],
                'state_id' => 1,
            ]);
        }
        // Cidades Piaui
        foreach($cidadesPiaui as $key => $c) {
            DB::table('city')->insert([
                'name' => $cidadesPiaui[$key],
                'state_id' => 3,
            ]);
        }
        // Cidades MAranhão
        foreach($cidadesMaranhao as $key => $c) {
            DB::table('city')->insert([
                'name' => $cidadesMaranhao[$key],
                'state_id' => 2,
            ]);
        }

        $listStore = [
            [
                'name' => 'CACAU SHOW',
                'address' => 'RUA:DR.JOÃO PESSOA, 618 CENTRO',
                'information' => 'RUA:DR.JOÃO PESSOA, 618 CENTRO',
                'city_id' => '77',
                'lat' => -6.359873,
                'lng' => -39.299174,
            ],
            [
                'name' => 'CACAU SHOW',
                'address' => 'RUA: FLORIANO PEIXOTO, 506 CENTRO',
                'information' => 'RUA: FLORIANO PEIXOTO, 506 CENTRO',
                'city_id' => '77',
                'lat' => -6.361392,
                'lng' => -39.297737,
            ],
            [
                'name' => 'CACAU SHOW',
                'address' => 'RUA SANTA LUZIA, 328 CENTRO',
                'information' => 'RUA SANTA LUZIA, 328 CENTRO',
                'city_id' => '77',
                'lat' => -7.203820,
                'lng' => -39.318303,
            ],
            [
                'name' => 'CACAU SHOW',
                'address' => 'AV. PADRE CICERO, 2555 TRIANGULO',
                'information' => 'AV. PADRE CICERO, 2555 TRIANGULO',
                'city_id' => '77',
                'lat' => -7.223437,
                'lng' => -39.324213,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:RODRIGUES JUNIOR, 1227, CENTRO',
                'information' => 'RUA:RODRIGUES JUNIOR, 1227, CENTRO',
                'city_id' => '149',
                'lat' => -4.969607,
                'lng' => -39.014824,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:MONSENHOR SALVIANO PINTO, 407A',
                'information' => 'RUA:MONSENHOR SALVIANO PINTO, 407A',
                'city_id' => '151',
                'lat' => -5.198290,
                'lng' => -39.294774,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:Fº GURGEL VALENTE, 182',
                'information' => 'RUA:Fº GURGEL VALENTE, 182',
                'city_id' => '4',
                'lat' => -6.096456,
                'lng' => -39.455160,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:QUEIROZ PESSOA, 86',
                'information' => 'RUA:QUEIROZ PESSOA, 86',
                'city_id' => '22',
                'lat' => -4.967555,
                'lng' => -39.027435,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA: NELSINHO LEAL, 71 CENTRO',
                'information' => 'RUA: NELSINHO LEAL, 71 CENTRO',
                'city_id' => '100',
                'lat' => -6.524742,
                'lng' => -39.526471,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'AV. DOS QUIXELOS, SUPER LAGOA',
                'information' => 'AV. DOS QUIXELOS, SUPER LAGOA',
                'city_id' => '77',
                'lat' => -6.354260,
                'lng' => -39.307163,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:ANT.PEDRO BENEVIDES, 42',
                'information' => 'RUA:ANT.PEDRO BENEVIDES, 42',
                'city_id' => '115',
                'lat' => -5.742840,
                'lng' => -39.627728,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:SANTA ROSA, 24',
                'information' => 'RUA:SANTA ROSA, 24',
                'city_id' => '135',
                'lat' => -6.213589,
                'lng' => -40.696257,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA: PROF. JOÃO COELHO, 31, CENTRO',
                'information' => 'RUA: PROF. JOÃO COELHO, 31, CENTRO',
                'city_id' => '77',
                'lat' => -6.362993,
                'lng' => -39.301422,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:EPITÁCIO PESSOA, 172',
                'information' => 'RUA:EPITÁCIO PESSOA, 172',
                'city_id' => '126',
                'lat' => -6.244228,
                'lng' => -38.914492,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'PRAÇA HENRIQUE ANDRADE, 13 CENTRO',
                'information' => 'PRAÇA HENRIQUE ANDRADE, 13 CENTRO',
                'city_id' => '172',
                'lat' => -6.003239,
                'lng' => -40.294039,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'AV.Fº FRANÇA CAMBRAIA, 279',
                'information' => 'AV.Fº FRANÇA CAMBRAIA, 279',
                'city_id' => '165',
                'lat' => -5.588535,
                'lng' => -39.372377,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:MONSENHOR MACEDO, 146A',
                'information' => 'RUA:MONSENHOR MACEDO, 146A',
                'city_id' => '101',
                'lat' => -6.749109,
                'lng' => -38.964714,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:VALDER VIANA, 123',
                'information' => 'RUA:VALDER VIANA, 123',
                'city_id' => '45',
                'lat' => -6.605337,
                'lng' => -39.061416,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'AV: CARLOS ROBERTO COSTA, 334',
                'information' => 'AV: CARLOS ROBERTO COSTA, 334',
                'city_id' => '77',
                'lat' => -6.368563,
                'lng' => -39.306365,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:DONDON FEITOSA, 73',
                'information' => 'RUA:DONDON FEITOSA, 73',
                'city_id' => '172',
                'lat' => -6.003366,
                'lng' => -40.294082,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA: EPITACIO PESSOA, 122 CENTRO',
                'information' => 'RUA: EPITACIO PESSOA, 122 CENTRO',
                'city_id' => '77',
                'lat' => -6.361736,
                'lng' => -39.298070,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA: ELICIO ABREU, 23',
                'information' => 'RUA: ELICIO ABREU, 23',
                'city_id' => '137',
                'lat' => -5.452968,
                'lng' => -39.716785,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:DUQUE DE CAXIAS, 30',
                'information' => 'RUA:DUQUE DE CAXIAS, 30',
                'city_id' => '183',
                'lat' => -6.794382,
                'lng' => -39.298258,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:DEOCLECIANO ARAGÃO, 154 CENTRO',
                'information' => 'RUA:DEOCLECIANO ARAGÃO, 154 CENTRO',
                'city_id' => '124',
                'lat' => -5.537621,
                'lng' => -40.775485,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA DR. RUI MAIA, 541 CENTRO',
                'information' => 'RUA DR. RUI MAIA, 541 CENTRO',
                'city_id' => '149',
                'lat' => -4.966300,
                'lng' => -39.018568,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA: EPITACIO PESSOA, 122 CENTRO',
                'information' => 'RUA: EPITACIO PESSOA, 122 CENTRO',
                'city_id' => '77',
                'lat' => -4.968413,
                'lng' => -39.012681,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'PRAÇA DA GRAÇA, 745 A',
                'information' => 'PRAÇA DA GRAÇA, 745 A',
                'city_id' => '150',
                'lat' => -2.903133,
                'lng' => -41.779228,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'AV.DEP. PINHEIRO MACHADO, 1397 SL 101',
                'information' => 'AV.DEP. PINHEIRO MACHADO, 1397 SL 101',
                'city_id' => '150',
                'lat' => -2.916761,
                'lng' => -41.753863,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:CORONEL JOSÉ NARCISIO',
                'information' => 'RUA:CORONEL JOSÉ NARCISIO',
                'city_id' => '150',
                'lat' => -2.903764,
                'lng' => -41.777283,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:ANT. DAMASCENO, 03 CENTRO',
                'information' => 'RUA:ANT. DAMASCENO, 03 CENTRO',
                'city_id' => '58',
                'lat' => -3.470113,
                'lng' => -41.557420,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'AV: SENADOR JOAQUIM PIRES, 1043',
                'information' => 'AV: SENADOR JOAQUIM PIRES, 1043',
                'city_id' => '118',
                'lat' => -2.881554,
                'lng' => -41.657141,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'AV: SÃO SEBASTIÃO, 3429',
                'information' => 'AV: SÃO SEBASTIÃO, 3429',
                'city_id' => '150',
                'lat' => -2.909154,
                'lng' => -41.747105,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'AV.NOGUEIRA ACIOLY, 1310',
                'information' => 'AV.NOGUEIRA ACIOLY, 1310',
                'city_id' => '76',
                'lat' => -6.402708,
                'lng' => -38.860654,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA:DR.PAULO RAMOS, 936 CENTRO',
                'information' => 'RUA:DR.PAULO RAMOS, 936 CENTRO',
                'city_id' => '16',
                'lat' => -7.534243,
                'lng' => -46.045697,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA: BARÃO DO RIO BRANCO, 604',
                'information' => 'RUA: BARÃO DO RIO BRANCO, 604',
                'city_id' => '173',
                'lat' => -3.370783,
                'lng' => -42.418644,
            ],
            [
                'name' => 'O BOTICARIO',
                'address' => 'RUA: BARÃO DO RIO BRANCO, 604 A',
                'information' => 'RUA: BARÃO DO RIO BRANCO, 604 A',
                'city_id' => '173',
                'lat' => -3.370783,
                'lng' => -42.418644,
            ],
            [
                'name' => 'MAGRELLA COLLECTION',
                'address' => 'RUA:DR.JOÃO PESSOA, 618 CENTRO',
                'information' => 'RUA:DR.JOÃO PESSOA, 618 CENTRO',
                'city_id' => '77',
                'lat' => -6.360159,
                'lng' => -39.299174,
            ],
            [
                'name' => 'TIM',
                'address' => 'RUA: FLORIANO PEIXOTO, 526',
                'information' => 'RUA: FLORIANO PEIXOTO, 526',
                'city_id' => '77',
                'lat' => -6.361544,
                'lng' => -39.297494,
            ],
            [
                'name' => 'AREZZO',
                'address' => 'AV PROFESSOR CARLOS CUNHA, 1000 LOJA 129',
                'information' => 'AV PROFESSOR CARLOS CUNHA, 1000 LOJA 129',
                'city_id' => '187',
                'lat' => -2.510706,
                'lng' => -44.285499,
            ],
            [
                'name' => 'AREZZO',
                'address' => 'AV DANIEL DE LA TOUCHE, 987 LOJA 320 G',
                'information' => 'AV DANIEL DE LA TOUCHE, 987 LOJA 320 G',
                'city_id' => '187',
                'lat' => -2.527412,
                'lng' => -44.255305,
            ],
            [
                'name' => 'AREZZO',
                'address' => 'AV ININGA, 1201 LOJA V 122 - JOQUEI CLUB',
                'information' => 'AV ININGA, 1201 LOJA V 122 - JOQUEI CLUB',
                'city_id' => '213',
                'lat' => -5.078307,
                'lng' => -42.794967,
            ],
            [
                'name' => 'AREZZO',
                'address' => 'AV RAUL LOPES, 1000 LOJA 206',
                'information' => 'AV RAUL LOPES, 1000 LOJA 206',
                'city_id' => '213',
                'lat' => -5.080702,
                'lng' => -42.794542,
            ],
            [
                'name' => 'AREZZO',
                'address' => 'AV NOSSA SENHORA DE FATIMA, 680',
                'information' => 'AV NOSSA SENHORA DE FATIMA, 680',
                'city_id' => '213',
                'lat' => -5.074309,
                'lng' => -42.791020,
            ],
            [
                'name' => 'AREZZO',
                'address' => 'AV SÃO LUIS REI DE FRANÇA, 08 LOJA 2064',
                'information' => 'AV SÃO LUIS REI DE FRANÇA, 08 LOJA 2064',
                'city_id' => '187',
                'lat' => -2.534176,
                'lng' => -44.225499,
            ],
            [
                'name' => 'AREZZO',
                'address' => 'AV MARECHAL CASTELO BRANCO, 911 LOJA 211',
                'information' => 'AV MARECHAL CASTELO BRANCO, 911 LOJA 211',
                'city_id' => '213',
                'lat' => -2.494437,
                'lng' => -44.229122,
            ],
            [
                'name' => 'CROCS',
                'address' => 'AV WASHINGTON SOARES, 85 LOJA 212',
                'information' => 'AV WASHINGTON SOARES, 85 LOJA 212',
                'city_id' => '59',
                'lat' => -3.777751,
                'lng' => -38.481135,
            ],
            [
                'name' => 'CROCS',
                'address' => 'AV DANIEL DE LA TOUCHE, 987 LOJA 301 L',
                'information' => 'AV DANIEL DE LA TOUCHE, 987 LOJA 301 L',
                'city_id' => '187',
                'lat' => -2.527410,
                'lng' => -44.255305,
            ],
        ];        

        foreach($listStore as $store) {
            DB::table('store')->insert([
                'name' => $store['name'],
                'address' => $store['address'],
                'information' => $store['information'],
                'city_id' => $store['city_id'],
                'lat' => $store['lat'],
                'lng' => $store['lng'],
            ]);
        }

    }
}
